[package]
name = "drift-ffi-sys"
version = "2.162.0"
edition = "2024"
description = "FFI bindings to drift program"

[lib]
crate-type = ["cdylib"]

[dependencies]
abi_stable = { version = "0.11", default-features = false }
anchor-lang = "1.1"
drift-program = { package = "drift", path = "../protocol-v2/programs/drift", features = [
    "mainnet-beta", "drift-rs"
] }
fxhash = "0.2.1"
serde_json = "=1.0.143"
