name: Build

on:
  pull_request:
    branches:
      - master
      - main
      - v1
    paths:
      - "**.rs"
      - "**.toml"
      - "**.lock"
      - ".github/workflows/*.yml"

jobs:
  check:
    runs-on: ubicloud
    timeout-minutes: 15
    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install ffi toolchain (1.76.0)
        run: |
          rustup install 1.76.0-x86_64-unknown-linux-gnu
          rustup default 1.76.0-x86_64-unknown-linux-gnu
          rustup component add rustfmt
      - name: fmt
        run: |
          cargo fmt --check
      - name: build
        run: |
          cargo check
